### ISSUE TITLE
NSMutableData的dataWithData会引起递归调用

### ISSUE THREAD

**Issue by Tang-YLL** [chong2vv/YDAvoidCrashKit#1]
系统版本: iOS15.5
代码版本号：0.1.7
引起递归的代码:
    NSMutableData *data = [NSMutableData dataWithData: [[NSData alloc] init]];
现象: 
    一直递归调用: +[NSData(YDAvoidCrash) avoidDataWithData:]

**Comment by x554960766** [comment]
是的 我这边也出现了 递归调用

**Comment by chong2vv** [comment]
暂时先用0.1.8，之前公司事太多一直没倒出空弄这个
